"""Persistence operations, not SQL sessions; each method is a transaction boundary."""

from orchestrator.domain.panel import PanelOverview
from contextlib import AbstractContextManager
from typing import Protocol, Mapping, Sequence
from orchestrator.domain.records import (
    Assignment,
    SwitchOperation,
    NodeAccess,
    LeaseState,
    CachedAccess,
    RetiredBinding,
    InventoryRecord,
)
from orchestrator.domain.inventory import NodeSettings
from orchestrator.domain.models import Node, Observation
from orchestrator.domain.contracts import SwitchRequest, TransportConfiguration


class SwitchJournal(Protocol):
    def pending(self, client_id: str) -> SwitchOperation | None: ...
    def history(
        self, client_id: str, operation_id: str
    ) -> tuple[SwitchOperation | None, float | None]: ...
    def queued(self, limit: int) -> list[str]: ...
    def touch(self, client_id: str) -> None: ...
    def state(self, operation: SwitchOperation, state: str) -> None: ...
    def request_disable(self, operation: SwitchOperation) -> None: ...
    def complete(self, row: Assignment, operation: SwitchOperation, remote_id: str) -> None: ...
    def reserve(
        self,
        row: Assignment,
        request: SwitchRequest,
        source: NodeAccess,
        observations: Sequence[Observation],
    ) -> SwitchOperation: ...


class LeaseJournal(Protocol):
    def state(self, node_id: str) -> LeaseState | None: ...
    def reserve(
        self, node_id: str, server_id: str, controller: str, sequence: int, deadline: float
    ) -> None: ...
    def verify(self, node_id: str) -> None: ...
    def fence(self, node_id: str, boot: str, deadline: float) -> None: ...
    def remember(self, row: Assignment, data: Mapping[str, object]) -> None: ...
    def deny(self, row: Assignment, value: bool) -> None: ...
    def cached(self, client_id: str) -> CachedAccess | None: ...
    def retire(self, row: Assignment) -> None: ...
    def restore_snapshot(
        self, node_id: str
    ) -> tuple[bool, list[RetiredBinding], list[Assignment]]: ...
    def cleaned(self, node_id: str, binding_key: str) -> None: ...
    def unfence(self, node_id: str) -> None: ...


class InventoryJournal(Protocol):
    def seed(self, initial: Sequence[NodeSettings]) -> None: ...
    def records(self) -> list[InventoryRecord]: ...
    def pinned(self, node_id: str) -> bool: ...
    def save(self, node_id: str, revision: int, configuration: str) -> None: ...


class Journal(Protocol):
    @property
    def switches(self) -> SwitchJournal: ...
    @property
    def leases(self) -> LeaseJournal: ...
    @property
    def inventory(self) -> InventoryJournal: ...
    def lock(self, identity: str) -> AbstractContextManager[None]: ...
    def rows(self) -> list[Assignment]: ...
    def get(
        self, external_id: str | None = None, client_id: str | None = None
    ) -> Assignment | None: ...
    def reserve(
        self,
        payload: Mapping[str, str],
        observations: Sequence[Observation],
        device_id: str | None = None,
        protocol: str = "amneziawg",
    ) -> Assignment: ...
    def bind(self, row: Assignment, remote_id: str) -> None: ...
    def record(self, row: Assignment, operation: str, outcome: str) -> None: ...
    def for_device(self, device_id: str) -> list[Assignment]: ...
    def configuration_revision(
        self, row: Assignment, configuration: TransportConfiguration, expires_at: str
    ) -> int: ...
    def diagnostic_counts(self) -> dict[str, int | float]: ...


class Credentials(Protocol):
    def resolve(self, config: NodeSettings) -> Node: ...
    def read(self, path: str) -> str: ...
    def allocate(self) -> str: ...
    def write(self, path: str, key: str) -> None: ...
    def discard(self, path: str) -> None: ...


class PanelReader(Protocol):
    def overview(self, node_offset: int, connection_offset: int) -> "PanelOverview": ...


class OperatorJournal(Protocol):
    def begin(self, command: dict, actor: str) -> dict: ...
    def finish(self, operation_id: str, result: dict, success: bool) -> None: ...
    def recent(self) -> list[dict]: ...


class PolicyEditor(Protocol):
    def read(self) -> dict: ...
    def save(self, expected_revision: str, policy: dict) -> dict: ...
